import { dir } from "i18next";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import { allowedLocales } from "@/lib/i18n/localizations";

import "../globals.css";

export async function generateStaticParams() {
  return allowedLocales.map((locale) => ({ locale }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={inter.className}>
        <main className="main-layout">
          <div className="main-layout-content">
            <Header locale={locale} />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
